[2024-02-15T16:14:40.222+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_success_dag.test_success_task manual__2024-02-15T16:13:45.104033+00:00 [queued]>
[2024-02-15T16:14:40.254+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_success_dag.test_success_task manual__2024-02-15T16:13:45.104033+00:00 [queued]>
[2024-02-15T16:14:40.257+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-02-15T16:14:40.312+0000] {taskinstance.py:2191} INFO - Executing <Task(KubernetesPodOperator): test_success_task> on 2024-02-15 16:13:45.104033+00:00
[2024-02-15T16:14:40.332+0000] {standard_task_runner.py:60} INFO - Started process 43 to run task
[2024-02-15T16:14:40.360+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'test_success_dag', 'test_success_task', 'manual__2024-02-15T16:13:45.104033+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/test_success_dag.py', '--cfg-path', '/tmp/tmp1sqrnnq_']
[2024-02-15T16:14:40.367+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask test_success_task
[2024-02-15T16:14:40.529+0000] {task_command.py:423} INFO - Running <TaskInstance: test_success_dag.test_success_task manual__2024-02-15T16:13:45.104033+00:00 [running]> on host test-success-dag-test-success-task-bbumis42
[2024-02-15T16:14:40.795+0000] {pod_generator.py:547} WARNING - Model file  does not exist
[2024-02-15T16:14:40.930+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='test_success_dag' AIRFLOW_CTX_TASK_ID='test_success_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-15T16:13:45.104033+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-15T16:13:45.104033+00:00'
[2024-02-15T16:14:40.953+0000] {pod.py:926} INFO - Building pod test-success-task-zo7f0iea with labels: {'dag_id': 'test_success_dag', 'task_id': 'test_success_task', 'run_id': 'manual__2024-02-15T161345.1040330000-b6b5df9f2', 'kubernetes_pod_operator': 'True', 'try_number': '1'}
[2024-02-15T16:14:40.972+0000] {base.py:83} INFO - Using connection ID 'kubernetes_default' for task execution.
[2024-02-15T16:14:41.605+0000] {pod.py:490} INFO - Found matching pod test-success-task-zo7f0iea with labels {'airflow_kpo_in_cluster': 'True', 'airflow_version': '2.8.1', 'dag_id': 'test_success_dag', 'kubernetes_pod_operator': 'True', 'run_id': 'manual__2024-02-15T161345.1040330000-b6b5df9f2', 'task_id': 'test_success_task', 'try_number': '1'}
[2024-02-15T16:14:41.611+0000] {pod.py:491} INFO - `try_number` of task_instance: 1
[2024-02-15T16:14:41.613+0000] {pod.py:492} INFO - `try_number` of pod: 1
[2024-02-15T16:14:41.659+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-success-task-zo7f0iea
[2024-02-15T16:14:43.012+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-success-task-zo7f0iea
[2024-02-15T16:14:44.225+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-success-task-zo7f0iea
[2024-02-15T16:14:45.399+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-success-task-zo7f0iea
[2024-02-15T16:14:46.678+0000] {pod_manager.py:460} INFO - [base] Hello World!

[2024-02-15T16:14:46.857+0000] {pod.py:785} INFO - Deleting pod: test-success-task-zo7f0iea
[2024-02-15T16:14:47.058+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=test_success_dag, task_id=test_success_task, execution_date=20240215T161345, start_date=20240215T161440, end_date=20240215T161447
[2024-02-15T16:14:47.162+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-15T16:14:47.345+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
