[2024-02-15T04:51:19.335+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_success_dag.test_success_task scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2024-02-15T04:51:19.367+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_success_dag.test_success_task scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2024-02-15T04:51:19.370+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-02-15T04:51:19.440+0000] {taskinstance.py:2191} INFO - Executing <Task(KubernetesPodOperator): test_success_task> on 2020-01-01 00:00:00+00:00
[2024-02-15T04:51:19.464+0000] {standard_task_runner.py:60} INFO - Started process 43 to run task
[2024-02-15T04:51:19.492+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'test_success_dag', 'test_success_task', 'scheduled__2020-01-01T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/test_success_dag.py', '--cfg-path', '/tmp/tmpsg4n5ug0']
[2024-02-15T04:51:19.500+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask test_success_task
[2024-02-15T04:51:19.777+0000] {task_command.py:423} INFO - Running <TaskInstance: test_success_dag.test_success_task scheduled__2020-01-01T00:00:00+00:00 [running]> on host test-success-dag-test-success-task-opue2rn1
[2024-02-15T04:51:20.078+0000] {pod_generator.py:547} WARNING - Model file  does not exist
[2024-02-15T04:51:20.251+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='test_success_dag' AIRFLOW_CTX_TASK_ID='test_success_task' AIRFLOW_CTX_EXECUTION_DATE='2020-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2020-01-01T00:00:00+00:00'
[2024-02-15T04:51:20.277+0000] {pod.py:926} INFO - Building pod test-success-task-2b4q7lpi with labels: {'dag_id': 'test_success_dag', 'task_id': 'test_success_task', 'run_id': 'scheduled__2020-01-01T0000000000-cc3b7db2b', 'kubernetes_pod_operator': 'True', 'try_number': '1'}
[2024-02-15T04:51:20.299+0000] {base.py:83} INFO - Using connection ID 'kubernetes_default' for task execution.
[2024-02-15T04:51:20.797+0000] {pod.py:490} INFO - Found matching pod test-success-task-2b4q7lpi with labels {'airflow_kpo_in_cluster': 'True', 'airflow_version': '2.8.1', 'dag_id': 'test_success_dag', 'kubernetes_pod_operator': 'True', 'run_id': 'scheduled__2020-01-01T0000000000-cc3b7db2b', 'task_id': 'test_success_task', 'try_number': '1'}
[2024-02-15T04:51:20.801+0000] {pod.py:491} INFO - `try_number` of task_instance: 1
[2024-02-15T04:51:20.803+0000] {pod.py:492} INFO - `try_number` of pod: 1
[2024-02-15T04:51:20.880+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-success-task-2b4q7lpi
[2024-02-15T04:51:21.972+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-success-task-2b4q7lpi
[2024-02-15T04:51:23.033+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-success-task-2b4q7lpi
[2024-02-15T04:51:24.119+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-success-task-2b4q7lpi
[2024-02-15T04:51:25.311+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-success-task-2b4q7lpi
[2024-02-15T04:51:26.542+0000] {pod_manager.py:460} INFO - [base] Hello World!

[2024-02-15T04:51:26.603+0000] {pod_manager.py:488} WARNING - Pod test-success-task-2b4q7lpi log read interrupted but container base still running
[2024-02-15T04:51:27.725+0000] {pod_manager.py:460} INFO - [base] Hello World!

[2024-02-15T04:51:27.869+0000] {pod.py:785} INFO - Deleting pod: test-success-task-2b4q7lpi
[2024-02-15T04:51:27.950+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=test_success_dag, task_id=test_success_task, execution_date=20200101T000000, start_date=20240215T045119, end_date=20240215T045127
[2024-02-15T04:51:28.070+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-15T04:51:28.145+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-02-15T16:14:40.223+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_success_dag.test_success_task scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2024-02-15T16:14:40.255+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_success_dag.test_success_task scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2024-02-15T16:14:40.258+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-02-15T16:14:40.314+0000] {taskinstance.py:2191} INFO - Executing <Task(KubernetesPodOperator): test_success_task> on 2020-01-01 00:00:00+00:00
[2024-02-15T16:14:40.332+0000] {standard_task_runner.py:60} INFO - Started process 43 to run task
[2024-02-15T16:14:40.360+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'test_success_dag', 'test_success_task', 'scheduled__2020-01-01T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/test_success_dag.py', '--cfg-path', '/tmp/tmp4tcyq4xh']
[2024-02-15T16:14:40.367+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask test_success_task
[2024-02-15T16:14:40.529+0000] {task_command.py:423} INFO - Running <TaskInstance: test_success_dag.test_success_task scheduled__2020-01-01T00:00:00+00:00 [running]> on host test-success-dag-test-success-task-sfi1zml2
[2024-02-15T16:14:40.795+0000] {pod_generator.py:547} WARNING - Model file  does not exist
[2024-02-15T16:14:40.931+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='test_success_dag' AIRFLOW_CTX_TASK_ID='test_success_task' AIRFLOW_CTX_EXECUTION_DATE='2020-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2020-01-01T00:00:00+00:00'
[2024-02-15T16:14:40.953+0000] {pod.py:926} INFO - Building pod test-success-task-oes7us7w with labels: {'dag_id': 'test_success_dag', 'task_id': 'test_success_task', 'run_id': 'scheduled__2020-01-01T0000000000-cc3b7db2b', 'kubernetes_pod_operator': 'True', 'try_number': '1'}
[2024-02-15T16:14:40.972+0000] {base.py:83} INFO - Using connection ID 'kubernetes_default' for task execution.
[2024-02-15T16:14:41.597+0000] {pod.py:490} INFO - Found matching pod test-success-task-oes7us7w with labels {'airflow_kpo_in_cluster': 'True', 'airflow_version': '2.8.1', 'dag_id': 'test_success_dag', 'kubernetes_pod_operator': 'True', 'run_id': 'scheduled__2020-01-01T0000000000-cc3b7db2b', 'task_id': 'test_success_task', 'try_number': '1'}
[2024-02-15T16:14:41.605+0000] {pod.py:491} INFO - `try_number` of task_instance: 1
[2024-02-15T16:14:41.608+0000] {pod.py:492} INFO - `try_number` of pod: 1
[2024-02-15T16:14:41.653+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-success-task-oes7us7w
[2024-02-15T16:14:43.016+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-success-task-oes7us7w
[2024-02-15T16:14:44.201+0000] {pod_manager.py:359} WARNING - Pod not yet started: test-success-task-oes7us7w
[2024-02-15T16:14:45.673+0000] {pod_manager.py:460} INFO - [base] Hello World!

[2024-02-15T16:14:45.794+0000] {pod_manager.py:593} INFO - Pod test-success-task-oes7us7w has phase Running
[2024-02-15T16:14:47.920+0000] {pod.py:785} INFO - Deleting pod: test-success-task-oes7us7w
[2024-02-15T16:14:48.023+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=test_success_dag, task_id=test_success_task, execution_date=20200101T000000, start_date=20240215T161440, end_date=20240215T161448
[2024-02-15T16:14:48.101+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-15T16:14:48.175+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
